<?php

/**
 * Maho Module Generator
 *
 * @copyright  Copyright (c) 2026 Mage Australia
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

declare(strict_types=1);

namespace MahoModuleGenerator\Artifact;

use MahoModuleGenerator\Spec;
use MahoModuleGenerator\Strings;
use MahoModuleGenerator\Tpl;

/**
 * composer.json, app/etc/modules registration, README, .gitignore, CI workflow.
 */
final class MetaFiles implements ArtifactGenerator
{
    #[\Override]
    public function generate(Spec $spec, Strings $strings): array
    {
        $module = $spec->moduleName();
        $vendorLower = strtolower($spec->module['vendor']);
        $nameKebab = Spec::kebab($spec->module['name']);

        $composer = [
            'name' => "$vendorLower/maho-module-$nameKebab",
            'license' => $spec->module['license'],
            'type' => 'maho-module',
            'description' => $spec->module['name'] . ' module for Maho (generated by maho-module-generator)',
            'require' => [
                'php' => '>=8.3',
                'mahocommerce/maho' => '^26.5',
            ],
            'extra' => [
                'maho-module-dir' => $spec->codeDir(),
            ],
        ];

        $depends = '';
        foreach ((array) $spec->module['depends'] as $dep) {
            $depends .= "                <$dep/>\n";
        }
        $modulesXml = Tpl::render(<<<'TPL'
<?xml version="1.0"?>
<config>
    <modules>
        <{{Module}}>
            <active>true</active>
            <codePool>{{Pool}}</codePool>
            <depends>
{{Depends}}            </depends>
        </{{Module}}>
    </modules>
</config>

TPL, [
            'Module' => $module,
            'Pool' => $spec->module['code_pool'],
            'Depends' => $depends,
        ]);

        $entityList = implode(', ', array_keys($spec->entities));
        $readme = Tpl::render(<<<'TPL'
# {{Module}}

Generated by [maho-module-generator](https://github.com/mageaustralia/maho-module-generator).

Entities: {{Entities}}

## Install

```bash
composer require {{ComposerName}}
./maho migrate
./maho cache:flush
composer dump-autoload
```

## Regenerating

This module was generated from a spec file. To regenerate after editing
the spec:

```bash
maho-module-gen generate path/to/spec.yaml --out .
```

Hand-edited files will be overwritten on regenerate - keep customisations
in child classes or fork the spec workflow deliberately.

TPL, [
            'Module' => $module,
            'Entities' => $entityList,
            'ComposerName' => $composer['name'],
        ]);

        $ci = <<<'YML'
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    uses: mageaustralia/maho-ci/.github/workflows/module-checks.yml@main
  lint:
    uses: mageaustralia/maho-module-generator/.github/workflows/lint.yml@main

YML;

        return [
            'composer.json' => json_encode($composer, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n",
            'app/etc/modules/' . $module . '.xml' => $modulesXml,
            'README.md' => $readme,
            '.gitignore' => "vendor/\ncomposer.lock\n.DS_Store\n",
            '.github/workflows/ci.yml' => $ci,
        ];
    }
}
